parameters:
    pim_import_export.validator.constraints.filter_data_validator.class: Pim\Bundle\ImportExportBundle\Validator\Constraints\FilterDataValidator

services:
    pim_import_export.validator.constraints.filter_data_validator:
        class: '%pim_import_export.validator.constraints.filter_data_validator.class%'
#        arguments:
#            - '@pim_catalog.repository.channel'
        tags:
            - { name: validator.constraint_validator, alias: filter_data_validator }
